# Generated by Django 2.2.3 on 2019-07-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CriminalID', models.IntegerField()),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Sex', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='male', max_length=6)),
                ('Address', models.CharField(max_length=100)),
                ('Height', models.CharField(max_length=6)),
                ('EyeColor', models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('brown', 'BROWN'), ('black', 'BLACK'), ('white', 'WHITE')], default='black', max_length=6)),
                ('Crime', models.CharField(max_length=100)),
                ('PoliceStation', models.CharField(max_length=100)),
                ('CriminalPhoto', models.FileField(default='settings.MEDIA_ROOT/documents/download.png', upload_to='documents/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
